Connecting...
Connected!
Setting: $RST=$
ok
Setting: $23=3
ok
Setting: $3=3
ok
Setting: $30=100
ok
Setting: $$
ok
Sending: ; Prepare Job
ok
Sending: M5 ; Laser Off
ok
Sending: G21 ; Millimeter
ok
Sending: G90 ; Absolute Positioning
ok
Sending: $H ; Homing
Traceback (most recent call last):
  File "/Users/merlinhof/Library/Python/3.9/lib/python/site-packages/serial/serialposix.py", line 575, in read
    buf = os.read(self.fd, size - len(read))
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/merlinhof/Desktop/vectorLaser/backend/./laser.py", line 56, in <module>
    feedback = ser.readline().decode('utf-8').strip()
  File "/Users/merlinhof/Library/Python/3.9/lib/python/site-packages/serial/serialposix.py", line 581, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: [Errno 6] Device not configured
